INSERT INTO RESTAURANT (restaurantName, phone, location, imageurl) VALUES
('Pizza Kottaram', '123-456-7890', 'Vellayambalom', 'https://example.com/pizza_palace.jpg'),
('Sushi Kada', '987-654-3210', 'Kowdiar', 'https://example.com/sushi_kada.jpg'),
('Njetikkal Mandhi Kada', '555-555-5555', 'Poojapura', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Howweda Chayakada', '555-555-5555', 'Palayam', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Ikkakkante Sarbath', '555-555-5555', 'Pattom', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Matcha Kudicha?', '555-555-5555', 'Kuravankonam', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Vedikkett Burger', '555-555-5555', 'Peyad', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Porotta Adich Keri Vaaa', '555-555-5555', 'Karamana', 'https://example.com/njetikkal_mandhi_kada.jpg'),
('Theeppori Birnani', '555-555-5555', 'Thiruvananthapuram', 'https://example.com/theeppori_biriyani.jpg');


INSERT INTO MENU_ITEMS (restaurantId, itemName, description, isVeg, cuisineType, price, imageurl) VALUES
(1, 'Hawaiian Pizza', 'Pizza with ham and pineapple', FALSE, 'Italian', 11.99, 'https://example.com/hawaiian_pizza.jpg'),
(1, 'Veggie Pizza', 'Pizza with assorted vegetables', TRUE, 'Italian', 9.99, 'https://example.com/veggie_pizza.jpg'),
(1, 'BBQ Chicken Pizza', 'Pizza with BBQ chicken and onions', FALSE, 'Italian', 12.99, 'https://example.com/bbq_chicken_pizza.jpg'),
(1, 'Four Cheese Pizza', 'Pizza with four types of cheese', TRUE, 'Italian', 10.99, 'https://example.com/four_cheese_pizza.jpg'),
(1, 'Meat Lovers Pizza', 'Pizza loaded with various meats', FALSE, 'Italian', 13.99, 'https://example.com/meat_lovers_pizza.jpg'),
(2, 'Salmon Nigiri', 'Fresh salmon over rice', FALSE, 'Japanese', 7.99, 'https://example.com/salmon_nigiri.jpg'),
(2, 'Tuna Sashimi', 'Fresh tuna slices', FALSE, 'Japanese', 8.99, 'https://example.com/tuna_sashimi.jpg'),
(2, 'Vegetable Sushi Roll', 'Roll with mixed vegetables', TRUE, 'Japanese', 5.99, 'https://example.com/vegetable_sushi_roll.jpg'),
(2, 'Shrimp Tempura Roll', 'Roll with shrimp tempura', FALSE, 'Japanese', 9.99, 'https://example.com/shrimp_tempura_roll.jpg'),
(2, 'Spicy Tuna Roll', 'Roll with spicy tuna', FALSE, 'Japanese', 8.99, 'https://example.com/spicy_tuna_roll.jpg'),
(3, 'Beef Mandhi', 'Spiced beef cooked with rice', FALSE, 'Indian', 10.99, 'https://example.com/beef_mandhi.jpg'),
(3, 'Fish Mandhi', 'Spiced fish cooked with rice', FALSE, 'Indian', 11.99, 'https://example.com/fish_mandhi.jpg'),
(3, 'Mutton Mandhi', 'Spiced mutton cooked with rice', FALSE, 'Indian', 12.99, 'https://example.com/mutton_mandhi.jpg'),
(3, 'Prawn Mandhi', 'Spiced prawns cooked with rice', FALSE, 'Indian', 13.99, 'https://example.com/prawn_mandhi.jpg'),
(3, 'Egg Mandhi', 'Spiced eggs cooked with rice', FALSE, 'Indian', 9.99, 'https://example.com/egg_mandhi.jpg'),
(4, 'Masala Chai', 'Spiced tea with milk', TRUE, 'Indian', 2.99, 'https://example.com/masala_chai.jpg'),
(4, 'Green Tea', 'Plain green tea', TRUE, 'Chinese', 2.49, 'https://example.com/green_tea.jpg'),
(4, 'Black Tea', 'Plain black tea', TRUE, 'British', 2.49, 'https://example.com/black_tea.jpg'),
(4, 'Lemon Tea', 'Tea with lemon', TRUE, 'Indian', 2.99, 'https://example.com/lemon_tea.jpg'),
(4, 'Ginger Tea', 'Tea with ginger', TRUE, 'Indian', 2.99, 'https://example.com/ginger_tea.jpg'),
(5, 'Rose Sarbath', 'Sweet rose flavored drink', TRUE, 'Indian', 3.99, 'https://example.com/rose_sarbath.jpg'),
(5, 'Lemon Sarbath', 'Tangy lemon drink', TRUE, 'Indian', 3.49, 'https://example.com/lemon_sarbath.jpg'),
(5, 'Mango Sarbath', 'Sweet mango drink', TRUE, 'Indian', 4.49, 'https://example.com/mango_sarbath.jpg'),
(5, 'Pineapple Sarbath', 'Pineapple flavored drink', TRUE, 'Indian', 4.49, 'https://example.com/pineapple_sarbath.jpg'),
(5, 'Orange Sarbath', 'Orange flavored drink', TRUE, 'Indian', 3.99, 'https://example.com/orange_sarbath.jpg'),
(6, 'Matcha Latte', 'Matcha powder with milk', TRUE, 'Japanese', 4.99, 'https://example.com/matcha_latte.jpg'),
(6, 'Iced Matcha', 'Cold matcha drink', TRUE, 'Japanese', 4.49, 'https://example.com/iced_matcha.jpg'),
(6, 'Matcha Smoothie', 'Matcha blended with fruits', TRUE, 'Japanese', 5.99, 'https://example.com/matcha_smoothie.jpg'),
(6, 'Matcha Tea', 'Traditional matcha tea', TRUE, 'Japanese', 3.99, 'https://example.com/matcha_tea.jpg'),
(6, 'Matcha Ice Cream', 'Matcha flavored ice cream', TRUE, 'Japanese', 4.99, 'https://example.com/matcha_ice_cream.jpg'),
(7, 'Cheese Burger', 'Burger with cheese', FALSE, 'American', 7.99, 'https://example.com/cheese_burger.jpg'),
(7, 'Veggie Burger', 'Burger with vegetables', TRUE, 'American', 6.99, 'https://example.com/veggie_burger.jpg'),
(7, 'Chicken Burger', 'Burger with chicken', FALSE, 'American', 8.99, 'https://example.com/chicken_burger.jpg'),
(7, 'Bacon Burger', 'Burger with bacon', FALSE, 'American', 9.99, 'https://example.com/bacon_burger.jpg'),
(7, 'Double Patty Burger', 'Burger with two patties', FALSE, 'American', 10.99, 'https://example.com/double_patty_burger.jpg'),
(8, 'Chicken Porotta', 'Porotta with chicken curry', FALSE, 'Indian', 6.99, 'https://example.com/chicken_porotta.jpg'),
(8, 'Beef Porotta', 'Porotta with beef curry', FALSE, 'Indian', 7.99, 'https://example.com/beef_porotta.jpg'),
(8, 'Coin Porotta', 'Porotta with vegetable curry', TRUE, 'Indian', 5.99, 'https://example.com/vegetable_porotta.jpg'),
(8, 'Bun Porotta', 'Porotta with egg', FALSE, 'Indian', 6.49, 'https://example.com/egg_porotta.jpg'),
(8, 'Mutton Porotta', 'Porotta with mutton curry', FALSE, 'Indian', 8.99, 'https://example.com/mutton_porotta.jpg'),
(9, 'Veg Biriyani', 'Vegetarian biriyani dishes', TRUE, 'Indian', 9.99, 'https://example.com/veg_thali.jpg'),
(9, 'Non-Veg Biriyani', 'Non-vegetarian biriyani dishes', FALSE, 'Indian', 12.99, 'https://example.com/non_veg_thali.jpg'),
(9, 'South Indian Biriyani', 'South Indian style biriyani', TRUE, 'Indian', 10.99, 'https://example.com/south_indian_thali.jpg'),
(9, 'North Indian Biriyani', 'North Indian style biriyani', FALSE, 'Indian', 11.99, 'https://example.com/north_indian_thali.jpg'),
(9, 'Rajasthani Biriyani', 'Rajasthani style biriyani', TRUE, 'Indian', 13.99, 'https://example.com/rajasthani_thali.jpg');