INSERT INTO RESTAURANT (restaurantName, phone, location, imageurl) VALUES
('Pizza Kottaram', '+91 82810978', 'Vellayambalom', '/static/images/cheesyPizza.jpg'),
('Sushi Kada', '+91 9876543210', 'Kowdiar', '/static/images/SalmonNigiri (1).jpg'),
('Njetikkal Mandhi Kada', '+91 9762109944', 'Poojapura', '/static/images/kuzhiMandi (1).jpg'),
('Howweda Chayakada', '+91 8213672201', 'Palayam', '/static/images/Chayakada.jpeg'),
('Ikkakkante Sarbath', '+91 7754890132', 'Pattom', '/static/images/LemonSarbath.jpg'),
('Matcha Kudicha?', '+91 9958181292', 'Kuravankonam', '/static/images/matcha_kudicho.jpeg'),
('Vedikkett Burger', '+91 9442207798', 'Peyad', '/static/images/ClassicCheeseBurger.jpg'),
('Porotta Adich Keri Vaaa', '+91 8654220157', 'Karamana', '/static/images/BunPorotta (1).jpg'),
('Theeppori Biriyani', '+91 9495673701', 'Thiruvananthapuram', '/static/images/ChickenBiriyani (1).jpg');


INSERT INTO MENU_ITEMS (restaurantId, itemName, description, isVeg, cuisineType, price, imageurl) VALUES
(1, 'Hawaiian Pizza', 'Pizza with ham and pineapple', FALSE, 'Italian', 299, '/static/images/HawaiianPizza (1).jpg'),
(1, 'Veggie Pizza', 'Pizza with assorted vegetables', TRUE, 'Italian', 199, '/static/images/vegPizza.jpg'),
(1, 'BBQ Chicken Pizza', 'Pizza with BBQ chicken and onions', FALSE, 'Italian', 499, '/static/images/bbqPizza (1).jpg'),
(1, 'Four Cheese Pizza', 'Pizza with four cheesy layers', TRUE, 'Italian', 600, '/static/images/cheesyPizza.jpg'),
(1, 'Meat Lovers Pizza', 'Pizza loaded with various meats', FALSE, 'Italian', 399, '/static/images/meatLoversPizza (1).jpg'),
(2, 'Salmon Nigiri', 'Fresh salmon over rice', FALSE, 'Japanese', 400, '/static/images/SalmonNigiri (1).jpg'),
(2, 'Tuna Sashimi', 'Fresh tuna slices', FALSE, 'Japanese', 560, '/static/images/TunaSashimi.jpg'),
(2, 'Vegetable Sushi Roll', 'Roll with mixed vegetables', TRUE, 'Japanese', 390, '/static/images/VegSushiRoll (1).jpg'),
(2, 'Shrimp Tempura Roll', 'Roll with shrimp tempura', FALSE, 'Japanese', 750, '/static/images/ShrimpTempuraRoll (1).jpg'),
(2, 'Spicy Tuna Roll', 'Roll with spicy tuna', FALSE, 'Japanese', 520, '/static/images/SpicyTuna (1).jpg'),
(3, 'Peri Peri Mandi', 'Arabian-style smoky, mandi rice with fiery Peri Peri Alfahm', FALSE, 'Indian', 899, '/static/images/periperiMandi.jpg'),
(3, 'Honey Chilli Alfahm Mandi', 'Mandi with AlFaham chicken coated in a sweet, and spicy honey-chilli sauce.', FALSE, 'Indian', 799, '/static/images/HoneyChilliMandi (1).jpg'),
(3, 'Kuzhi Mandi', 'Slow-cooked meat and mandi rice prepared together in a charcoal-fired underground pit ', FALSE, 'Indian', 750, '/static/images/kuzhiMandi (1).jpg'),
(3, 'Mutton Mandi', 'Spiced tender mutton served with mandi rice', FALSE, 'Indian', 820, '/static/images/muttonMandi (1).jpg'),
(3, 'Beef Mandi', 'Spiced slow cooked beef with mandi rice', FALSE, 'Indian',900, '/static/images/beefMandi (1).jpg'),
(4, 'Masala Chai', 'Spiced tea with milk', TRUE, 'Indian',40, '/static/images/masalaChai.jpg'),
(4, 'Green Tea', 'Plain green tea', TRUE, 'Chinese', 25, '/static/images/greentea (1).jpg'),
(4, 'Black Tea', 'Plain black tea', TRUE, 'British', 15, '/static/images/blackTea.jpg'),
(4, 'Lemon Tea', 'Tea with lemon', TRUE, 'Indian', 25, '/static/images/lemonTea (1).jpg'),
(4, 'Ginger Tea', 'Tea with ginger', TRUE, 'Indian',30, '/static/images/GingerTea (1).jpg'),
(5, 'Rose Sarbath', 'Sweet rose flavored drink', TRUE, 'Indian', 40, '/static/images/RoseSarbath (1).jpg'),
(5, 'Lemon Sarbath', 'Tangy lemon drink', TRUE, 'Indian', 30, '/static/images/LemonSarbath.jpg'),
(5, 'Mango Sarbath', 'Sweet mango drink', TRUE, 'Indian', 90, '/static/images/MangoSarbath (1).jpg'),
(5, 'Pineapple Sarbath', 'Pineapple flavored drink', TRUE, 'Indian', 85, '/static/images/PineappleSarbath (1).jpg'),
(5, 'Orange Sarbath', 'Orange flavored drink', TRUE, 'Indian', 65, '/static/images/OrangeSarbath (1).jpg'),
(6, 'Matcha Latte', 'Matcha powder with milk', TRUE, 'Japanese', 130, '/static/images/MatchaLatte.jpg'),
(6, 'Iced Matcha', 'Cold matcha drink', TRUE, 'Japanese', 140, '/static/images/IcedMatcha.jpg'),
(6, 'Matcha Smoothie', 'Matcha blended with fruits', TRUE, 'Japanese', 155, '/static/images/MatchaSmoothie.jpg'),
(6, 'Matcha Tea', 'Traditional matcha tea', TRUE, 'Japanese', 160, '/static/images/MatchaTea (1).jpg'),
(6, 'Matcha Ice Cream', 'Matcha flavored ice cream', TRUE, 'Japanese', 225, '/static/images/MatchaIcecream (1).jpg'),
(7, 'Classic Cheese Burger', 'American hamburger topped with a slice of melted cheese', FALSE, 'American', 190, '/static/images/ClassicCheeseBurger.jpg'),
(7, 'Veggie Burger', 'Burger with vegetable patty', TRUE, 'American', 399, '/static/images/VeggieBurger.jpg'),
(7, 'Stuffed Chicken Burger', 'Burger with grilled or fried chicken patty', FALSE, 'American', 580, '/static/images/StuffedChickenBurger (1).jpg'),
(7, 'Bacon Burger', 'A cheeseburger topped with crispy bacon.', FALSE, 'American', 850, '/static/images/BaconBurger (1).jpg'),
(7, 'Double Patty Burger', 'Burger with two meat patties', FALSE, 'American',760 , '/static/images/DoublePattyBurger (1).jpg'),
(8, 'Chicken Porotta', 'Porotta with nadan chicken curry', FALSE, 'Indian', 299, '/static/images/ChickenPorotta (1).jpg'),
(8, 'Beef Porotta', 'Porotta with shappu beef curry', FALSE, 'Indian', 360, '/static/images/BeefPorotta (1).jpg'),
(8, 'Coin Porotta', 'Coin shaped crispy soft porotta', TRUE, 'Indian',45, '/static/images/CoinPorotta (1).jpg'),
(8, 'Bun Porotta', 'Thick fluffy Madurai style Porotta', FALSE, 'Indian',50, '/static/images/BunPorotta (1).jpg'),
(8, 'Mutton Porotta', 'Porotta with spicy mutton curry', FALSE, 'Indian',390, '/static/images/MuttonPorotta (1).jpg'),
(9, 'Veg Biriyani', 'Long grain basmati rice layered with mixed vegetables', TRUE, 'Indian',200, '/static/images/VegBiriyani (1).jpg'),
(9, 'Chicken Biriyani', 'Tender marinated chicken layered with fragrant basmati rice', FALSE, 'Indian', 280, '/static/images/ChickenBiriyani (1).jpg'),
(9, 'Thalassery Dum Biriyani', 'Malabar style biriyani rich in masala', TRUE, 'Indian',350, '/static/images/ThalasseriDumBiriyani (1).jpg'),
(9, 'Dindigul Thalapakati Biriyani', 'Authentic South Indian Tamil Nadu biriyani', FALSE, 'Indian',389, '/static/images/DindigulThalapakatiBiriyani (1).jpg'),
(9, 'Aasife Biriyani', 'Authentic, aromatic, and rich Mughal-style biryani', TRUE, 'Indian', 295, '/static/images/AasifeBiriyani (1).jpg');