CREATE DATABASE IF NOT EXISTS FOOD_DELIVERY;
USE FOOD_DELIVERY;

CREATE TABLE IF NOT EXISTS CUSTOMER (
  customerId INT AUTO_INCREMENT PRIMARY KEY,
  fname VARCHAR(15) NOT NULL,
  lname VARCHAR(15) NOT NULL,
  midname VARCHAR(15),
  email VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  houseName VARCHAR(20) NOT NULL,
  street VARCHAR(20) NOT NULL,
  city VARCHAR(20) NOT NULL,
  pincode INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESTAURANT(
  restaurantId INT AUTO_INCREMENT PRIMARY KEY,
  restaurantName VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  location VARCHAR(255) NOT NULL,
  imageurl VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MENU_ITEMS(
  itemId INT AUTO_INCREMENT PRIMARY KEY,
  restaurantId INT NOT NULL,
  itemName VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  isVeg BOOLEAN NOT NULL,
  cuisineType VARCHAR(50) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  imageurl VARCHAR(255) NOT NULL,
  FOREIGN KEY (restaurantId) REFERENCES RESTAURANT(restaurantId)
);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS(
    detailId INT AUTO_INCREMENT PRIMARY KEY,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    itemId INT NOT NULL,
    orderId INT NOT NULL,
    FOREIGN KEY (itemId) REFERENCES MENU_ITEMS(itemId),
    FOREIGN KEY (orderId) REFERENCES ORDERS(orderId)
    );

CREATE TABLE IF NOT EXISTS ORDERS(
    orderId INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    totalAmount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    customerId INT NOT NULL,
    restaurantId INT NOT NULL,
    FOREIGN KEY (customerId) REFERENCES CUSTOMER(customerId),
    FOREIGN KEY (restaurantId) REFERENCES RESTAURANT(restaurantId)
    );

CREATE TABLE IF NOT EXISTS CART(
  cartId INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT NOT NULL,
  itemId INT NOT NULL,
  quantity INT NOT NULL,
  totalAmount DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (customerId) REFERENCES CUSTOMER(customerId),
  FOREIGN KEY (itemId) REFERENCES MENU_ITEMS(itemId)
);

CREATE TABLE IF NOT EXISTS BILLING(
  billingId INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  mode VARCHAR(50) NOT NULL,
  totalAmount DECIMAL(10,2) NOT NULL,
  timestamp DATETIME NOT NULL,
  FOREIGN KEY (orderId) REFERENCES ORDERS(orderId)
);

CREATE TABLE IF NOT EXISTS RATING(
    ratingId INT AUTO_INCREMENT PRIMARY KEY,
    customerId INT NOT NULL,
    restaurantId INT NOT NULL,
    rating INT,
    reviewText VARCHAR(255),
    FOREIGN KEY (customerId) REFERENCES CUSTOMER(customerId),
    FOREIGN KEY (restaurantId) REFERENCES RESTAURANT(restaurantId)
);

